// menu suggestions
let suggestions = [
    "Grilled Salmon",
    "Garlic Butter Baked Salmon",
    "Salmon Pasta In Parmesan Cream Sauce",
    "Fiesta Salmon Rice Bowls",
    "Baked Cajun Parmesan Salmon",
    "Salmon In Sun Dried Tomato Cream Sauce With Pearl Couscous",
    "5-Ingredient Asian Grilled Salmon Marinade",
    "Salmon Cakes with Roasted Red Bell Pepper Sauce",
    "Salmon Nicoise Salad",
    "Stuffed Pork Loin",
    "Instant Pot Pork Chops",
    "French Onion Pork Chops",
    "Air Fryer Pork Chops",
    "Glazed Pork Tenderloin",
    "Roast Pork Tenderloin",
    "Garlic Rosemary Pork Chops",
    "Instant Pot Pulled Pork",
    "Baked Pork Chops",
    "Chicken Piccata",
    "Creamy Tomato Chicken Skillet Dinner",
    "One Pan Honey Mustard Chicken and Vegetables",
    "Stovetop Butter Chicken",
    "Lemon Chicken",
    "Pesto Chicken Bruschetta",
    "Chicken Empanadas",
    "Buffalo Chicken Bites with Blue Cheese Dressing",
    "Roasted Salsa Verde Chicken Nachos",
    "Thai Basil Beef",
    "Gingery Ground Beef (Soboro Donburi)",
    "Crock-Pot Taco Meat",
    "Classic Cheese Burger with Secret Sauce",
    "Patty Melt",
    "Meatball Sub Sandwich",
    "Beef Sliders with Sun-Dried Tomato Mayo and Spicy Pickles",
    "Low-Carb Bacon Burger with Guacamole",
    "Swedish Meatballs",
    "Walnut and Lentil Bolognese",
    "Vegetable Soup",
    "Vegan Roasted Sweet Potato Salad",
    "Shaved Brussels Sprout Salad with Creamy Maple Dressing",
    "Vegetarian Burrito Bowl with Avocado Crema",
    "Green Curry Buddha Bowl",
    "Creamy Goat Cheese Polenta With Ratatouille",
    "Curried Cauliflower Quinoa Salad",
    "Curried Pumpkin Soup",
];

let suggestions2 = [
    "Buttermilk Pancakes",
    "Trail Mix Pancakes",
    "Dutch Baby Pancake",
    "Banana Walnut Cake",
    "Baileys Chocolate Bundt Cake",
    "Joanna’s Lemon Olive Oil Cake",
    "Cookie Brittle",
    "Salty Dark and Milk Chocolate Skillet Cookie",
    "Crinkle Cookies with Peppermint Cream",
    "Vegan Mint Chip Ice Cream",
    "Salted Caramel Apple Sundae",
    "Coconut Cream Popsicles With Vanilla",
];
